<a href="https://colab.research.google.com/github/Carambolushka/Bioinformatic-contest/blob/main/task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import itertools

In [ ]:
!wget 'https://stepik.org/media/attachments/lesson/541850/3.zip'

--2021-06-18 19:15:48--  https://stepik.org/media/attachments/lesson/541850/3.zip
Resolving stepik.org (stepik.org)... 13.69.75.239
Connecting to stepik.org (stepik.org)|13.69.75.239|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 617752 (603K) [application/zip]
Saving to: ‘3.zip’

3.zip               100%[===================>] 603.27K   654KB/s    in 0.9s    

2021-06-18 19:15:50 (654 KB/s) - ‘3.zip’ saved [617752/617752]



In [ ]:
!unzip /content/3.zip

Archive:  /content/3.zip
  inflating: 3.txt                   


In [ ]:
test_file = open('/content/3.txt', 'r')

In [ ]:
test = []
for line in test_file.readlines():
    test += [line.split()]

In [ ]:
test_file.close()

In [ ]:
number_of_tests = int(test[0][0])
print(number_of_tests)

2


In [ ]:
m_mass

In [ ]:
result = open('result.txt', 'w')
for i in range(number_of_tests):
    print(f'работа с {i} тестом')
    # enter the 1 example 
    numbers = test[1::4][i] 

    m_mass = test[2::4][i]
    k_mass = test[3::4][i]
    s_signal = test[4::4][i]
    print(f'длина m {len(m_mass)}')
    print(f'длина k {len(k_mass)}')
    print(f'длина s {len(s_signal)}')
    

    #create matrix with all combinations
    matr = np.array(list(itertools.product([float(i) for i in (m_mass)], [float(j) for j in k_mass])))
    
    #create table with indexis of combined
    index_m = [[float(j) for j in m_mass].index(k)+1 for k in matr.T[0]] #[[float(j) for j in test[2]].index(k)+1 for k in matr.T[0]]
    index_k = [[float(j) for j in k_mass].index(k)+1 for k in matr.T[1]]
               
    #create sum_matrix and vocabulary with sum_matrix and indexis
    matr_sum = matr.sum(axis=1)
    voc = {}
    for i in range(len(matr_sum)):
        voc[matr_sum[i]] = [index_m[i], index_k[i]]

    # create positive vocabulary
    voc_positive = {k: v for k, v in voc.items() if k>=0}
    
    #now i should count delta for each key in vocabulary
    
    matr_sum_positive = matr_sum[matr_sum>=0]

    float_s_signal = [float(j) for j in s_signal]
    counter = 0
    for i in (float_s_signal):
        if counter%1000 ==0:
            print(counter, '!!!!!!!!!!!!!!!!!!!!!!!!')
        counter += 1
        #deltas = []

        deltas = abs(matr_sum_positive - i)
        
        best_delta = np.min(deltas)
        

        for_print = list(voc_positive.get(matr_sum_positive[tuple(deltas).index(best_delta)]))
        
        print(*for_print, file=result)
result.close()


84000 !!!!!!!!!!!!!!!!!!!!!!!!
85000 !!!!!!!!!!!!!!!!!!!!!!!!
86000 !!!!!!!!!!!!!!!!!!!!!!!!
87000 !!!!!!!!!!!!!!!!!!!!!!!!
88000 !!!!!!!!!!!!!!!!!!!!!!!!
89000 !!!!!!!!!!!!!!!!!!!!!!!!
90000 !!!!!!!!!!!!!!!!!!!!!!!!
91000 !!!!!!!!!!!!!!!!!!!!!!!!
92000 !!!!!!!!!!!!!!!!!!!!!!!!
93000 !!!!!!!!!!!!!!!!!!!!!!!!
94000 !!!!!!!!!!!!!!!!!!!!!!!!
95000 !!!!!!!!!!!!!!!!!!!!!!!!
96000 !!!!!!!!!!!!!!!!!!!!!!!!
97000 !!!!!!!!!!!!!!!!!!!!!!!!
98000 !!!!!!!!!!!!!!!!!!!!!!!!
99000 !!!!!!!!!!!!!!!!!!!!!!!!


In [ ]:
!cp '/content/result.txt' '/content/drive/MyDrive/Programming_All/result.txt'

In [ ]:
voc_positive

{0.500002: [2, 1], 0.5000020000000001: [1, 2], 1.500002: [1, 1]}

In [ ]:
deltas

[1.0000010000000001,
 1.0000000000287557e-06,
 9.999999999177334e-07,
 1.0,
 1.1102230246251565e-16,
 0.0]

In [ ]:
matr_sum_positive

array([1.500002, 0.500002, 0.500002])

In [ ]:
a=[1,2,3, 4,1,0.5]

c=[]
[abs(i-1) for i in a]

[0, 1, 2, 3, 0, 0.5]

In [ ]:
b=[np.array([1.000001e+00, 1.000000e-06, 1.000000e-06])]
np.min(b)

1e-06

In [ ]:
number_of_tests = int(test[0][0])
print(number_of_tests)
number_of_m = int(test[1][0])
print(number_of_m)
number_of_k = int(test[1][1])
print(number_of_k)
number_of_s = int(test[1][2])
print(number_of_s)

3
2
2
5


In [ ]:
matr = np.array(list(itertools.product([float(i) for i in (test[2])], [float(j) for j in test[3]])))

In [ ]:
print(matr)

[[ 1.000002e+00  5.000000e-01]
 [ 1.000002e+00 -5.000000e-01]
 [ 2.000000e-06  5.000000e-01]
 [ 2.000000e-06 -5.000000e-01]]


In [ ]:
index_m = [[float(j) for j in test[2]].index(k)+1 for k in matr.T[0]]

In [ ]:
index_m

[1, 1, 2, 2]

In [ ]:
index_k = [[float(j) for j in test[3]].index(k)+1 for k in matr.T[1]]

In [ ]:
matr_sum = matr.sum(axis=1)

In [ ]:
matr_sum

array([ 1.500002,  0.500002,  0.500002, -0.499998])

In [ ]:
voc = {}
for i in range(len(matr_sum)):
    voc[matr_sum[i]] = [index_m[i], index_k[i]]
print(voc)

{1.500002: [1, 1], 0.5000020000000001: [1, 2], 0.500002: [2, 1], -0.499998: [2, 2]}


In [ ]:
#{k: v for k, v in my_dict.items() if k != 1}
voc_positive = {k: v for k, v in voc.items() if k>=0}

In [ ]:
voc_positive

{0.500002: [2, 1], 0.5000020000000001: [1, 2], 1.500002: [1, 1]}

In [ ]:
test[4]

['0.500001', '0.500002', '0.500003', '1.000000', '0.000001']

In [ ]:
[min(filter(lambda val: val >= 0, k)) for k in all_res]

[]